lua     = ">=5.1"
package = "expantanum"
version = "0.1.0"

[description]
    labels     = ["bignum", "googology"]
    license    = "MIT"
    maintainer = "Rhelvetican"
    summary    = "ExpantaNum.js port for Lua."

[dependencies]
    # Add your dependencies here
    # `busted = ">=2.0"`

[run]
    args = ["src/main.lua"]

[build]
    type = "builtin"

